-- AlterTable
ALTER TABLE `organizations` ADD COLUMN `currentPeriodEnd` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN `subscriptionStatus` ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED') NOT NULL DEFAULT 'TRIALING';
