// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // DATABASE_URL must be a MySQL connection string, for example:
  // mysql://user:password@db:3306/database
  datasource: {
    url: env("DATABASE_URL"),
  },
});
