/*
  Warnings:

  - The values [CREATED,UPDATED,STATUS_CHANGED,PRIORITY_CHANGED,ASSIGNED,UNASSIGNED,COMMENTED] on the enum `task_events_type` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `task_events` MODIFY `type` ENUM('TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_STATUS_CHANGED', 'TASK_PRIORITY_CHANGED', 'ASSIGNMENT_CREATED', 'ASSIGNMENT_UPDATED', 'ASSIGNMENT_DELETED', 'COMMENT_CREATED', 'COMMENT_UPDATED', 'COMMENT_DELETED', 'PROGRESS_LOGGED', 'SUBTASK_ADDED', 'SUBTASK_REMOVED') NOT NULL;
