/*
  Warnings:

  - The values [TASK_UPDATED,ASSIGNMENT_UPDATED,PHOTO_UPLOADED,PHOTO_DELETED] on the enum `task_events_type` will be removed. If these variants are still used in the database, this will fail.

*/
-- Remove obsolete event types before altering the enum
DELETE FROM `task_events` WHERE `type` IN ('TASK_UPDATED', 'ASSIGNMENT_UPDATED', 'PHOTO_UPLOADED', 'PHOTO_DELETED');

-- AlterTable
ALTER TABLE `task_events` MODIFY `type` ENUM('TASK_CREATED', 'TASK_TITLE_CHANGED', 'TASK_DESCRIPTION_CHANGED', 'TASK_DUE_DATE_CHANGED', 'TASK_PRIORITY_CHANGED', 'TASK_PROJECT_CHANGED', 'TASK_STATUS_CHANGED', 'TASK_DELETED', 'ASSIGNMENT_CREATED', 'ASSIGNMENT_DELETED', 'COMMENT_CREATED', 'COMMENT_UPDATED', 'COMMENT_DELETED', 'PROGRESS_LOGGED', 'SUBTASK_ADDED', 'SUBTASK_REMOVED', 'RECURRING_TEMPLATE_CREATED', 'RECURRING_TEMPLATE_UPDATED', 'RECURRING_TEMPLATE_DEACTIVATED', 'RECURRING_INSTANCE_GENERATED') NOT NULL;
